<html>
<title>
</title>
<head>
<link rel="stylesheet" type="text/css" href="emailsent.css">
<link rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Ubuntu">
<?php
if(!isset($_SERVER['HTTP_REFERER'])){
    // redirect them to your desired location
    header('location:/index.php');
    exit;
}

?>
</head>
<body>

<!--Load Navbar Components.-->

<!--Main Page Conents-->

<p>Sucess! Your email is being sent super quickly through the web!</p>

<div class ="content">
  <div class="loadingio-spinner-rolling-4krveg8al13">
    <div class="ldio-la3j1pg7i1">
      <div>
      </div>
    </div>
  </div>
</div>

<style type="text/css">

.content {
	background: none;
	width: 100%;
  height: auto;
	margin-top: 25px;
  margin-left: auto;
  margin-right: auto;
}

@keyframes ldio-la3j1pg7i1 {
  0% { transform: translate(-50%,-50%) rotate(0deg); }
  100% { transform: translate(-50%,-50%) rotate(360deg); }
}
.ldio-la3j1pg7i1 div {
  position: absolute;
  width: 120px;
  height: 120px;
  border: 20px solid #e15b64;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-la3j1pg7i1 div {
  animation: ldio-la3j1pg7i1 1s linear infinite;
  top: 100px;
  left: 100px
}
.loadingio-spinner-rolling-4krveg8al13 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-la3j1pg7i1 {
  width: 100%;
  height: 100%;
  left: 50%;
  margin-left: -6em;
  position: fixed;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-la3j1pg7i1 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>

<p>You will be redirected to the homepage...</p>



<script>
window.location.hash="no-back-button";
window.location.hash="Again-No-back-button";//again because google chrome don't insert first hash into history
window.onhashchange=function(){window.location.hash="no-back-button";}

setTimeout(function(){
   window.location.href = 'index.php';
}, 5000);
</script>


</body>
</html>
